version: '3.8'

services:
  frontend:
    build: ./fr-administration-front
    ports:
      - "80:80"
    volumes:
      - ./fr-administration-front:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./fr-administration-back
    ports:
      - "3000:3000"
    volumes:
      - ./fr-administration-back:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: mot_de_passe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports: 
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres-data: